receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    format: json
    tls:
      insecure: true
    # tenant_id: "example"
    labels:
      resource:
        container.name: "container_name"
        service.name: "service_name"
        service.version: "service_version"
        service.instance.id: "service_instance_id"

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
